-- OON Cold Cover + Proof Vault — initial schema
-- Conventions:
--   * ids are TEXT (prefixed random ids generated by the app)
--   * timestamps are ISO-8601 UTC strings
--   * tables marked APPEND-ONLY have triggers that abort UPDATE and DELETE.
--     This protects against ordinary application code paths. It is NOT absolute
--     immutability: anyone with direct write access to the database file can drop
--     triggers. The event hash chain (see ledger_events) makes such tampering
--     detectable by `npm run verify-ledger`.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------- users / auth
CREATE TABLE users (
  id                TEXT PRIMARY KEY,
  email             TEXT NOT NULL UNIQUE,
  display_name      TEXT NOT NULL,
  password_hash     TEXT NOT NULL,
  owner_operator_id TEXT REFERENCES owner_operators(id),
  active            INTEGER NOT NULL DEFAULT 1,
  is_demo           INTEGER NOT NULL DEFAULT 0,
  created_at        TEXT NOT NULL
);

CREATE TABLE user_roles (
  user_id TEXT NOT NULL REFERENCES users(id),
  role    TEXT NOT NULL CHECK (role IN ('OWNER_OPERATOR','QUALIFICATION_OFFICER','DISPATCHER','FINANCE','ADMIN','READ_ONLY_AUDITOR')),
  PRIMARY KEY (user_id, role)
);

CREATE TABLE sessions (
  token_hash TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id),
  csrf_token TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);

-- ---------------------------------------------------------------- policy (APPEND-ONLY)
CREATE TABLE policy_versions (
  version        INTEGER PRIMARY KEY,
  document_code  TEXT NOT NULL,
  effective_date TEXT NOT NULL,
  config_json    TEXT NOT NULL,
  change_note    TEXT NOT NULL,
  created_by     TEXT REFERENCES users(id),
  created_at     TEXT NOT NULL,
  config_hash    TEXT NOT NULL
);

-- ---------------------------------------------------------------- onboarding profile (mutable projections; every change is also a ledger event)
CREATE TABLE owner_operators (
  id               TEXT PRIMARY KEY,
  legal_name       TEXT NOT NULL,
  contact_name     TEXT,
  contact_phone    TEXT,
  contact_email    TEXT,
  base_city        TEXT,
  base_state       TEXT,
  dot_number       TEXT,
  mc_number        TEXT,
  submitted_at     TEXT,
  is_demo          INTEGER NOT NULL DEFAULT 0,
  created_by       TEXT,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);

CREATE TABLE drivers (
  id                TEXT PRIMARY KEY,
  owner_operator_id TEXT NOT NULL REFERENCES owner_operators(id),
  full_name         TEXT NOT NULL,
  license_class     TEXT,
  license_status    TEXT,
  license_state     TEXT,
  license_expires   TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);

CREATE TABLE trucks (
  id                        TEXT PRIMARY KEY,
  owner_operator_id         TEXT NOT NULL REFERENCES owner_operators(id),
  label                     TEXT NOT NULL,
  year                      INTEGER,
  make                      TEXT,
  model                     TEXT,
  vin                       TEXT,
  gvwr_lbs                  INTEGER,
  gcwr_lbs                  INTEGER,
  tow_rating_lbs            INTEGER,
  hitch_class               TEXT,
  hitch_type                TEXT,
  registration_state        TEXT,
  registration_number       TEXT,
  registration_expires      TEXT,
  auto_liability_usd        INTEGER,
  cargo_coverage_usd        INTEGER,
  insurance_effective       TEXT,
  insurance_expires         TEXT,
  created_at                TEXT NOT NULL,
  updated_at                TEXT NOT NULL
);

CREATE TABLE cold_assets (
  id                   TEXT PRIMARY KEY,
  owner_operator_id    TEXT NOT NULL REFERENCES owner_operators(id),
  asset_type           TEXT NOT NULL,
  unit_id              TEXT NOT NULL,
  reefer_make          TEXT,
  reefer_model         TEXT,
  stated_temp_min_f    REAL,
  stated_temp_max_f    REAL,
  gross_weight_lbs     INTEGER,
  required_hitch_type  TEXT,
  temp_logger_details  TEXT,
  security_details     TEXT,
  inspection_date      TEXT,
  registration_info    TEXT,
  -- power the reefer unit requires (structured, never inferred from connector names)
  req_voltage_min      INTEGER,
  req_voltage_max      INTEGER,
  req_phase            TEXT,
  req_amperage         INTEGER,
  inlet_connector      TEXT,
  shore_power_capable  INTEGER,
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL
);

CREATE TABLE power_configs (
  id                   TEXT PRIMARY KEY,
  owner_operator_id    TEXT NOT NULL REFERENCES owner_operators(id),
  label                TEXT NOT NULL,
  generator_make       TEXT,
  generator_model      TEXT,
  continuous_kw        REAL,
  fuel_notes           TEXT,
  voltage              INTEGER,
  phase                TEXT,
  amperage             INTEGER,
  receptacle_connector TEXT,
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL
);

CREATE TABLE power_adapters (
  id                TEXT PRIMARY KEY,
  owner_operator_id TEXT NOT NULL REFERENCES owner_operators(id),
  power_config_id   TEXT REFERENCES power_configs(id),
  from_connector    TEXT NOT NULL,
  to_connector      TEXT NOT NULL,
  rated_amperage    INTEGER,
  rated_voltage     INTEGER,
  description       TEXT,
  created_at        TEXT NOT NULL
);

-- ---------------------------------------------------------------- documents (private storage metadata)
CREATE TABLE documents (
  id                 TEXT PRIMARY KEY,
  owner_operator_id  TEXT REFERENCES owner_operators(id),
  job_id             TEXT REFERENCES jobs(id),
  category           TEXT NOT NULL,
  original_filename  TEXT NOT NULL,
  mime_type          TEXT NOT NULL,
  size_bytes         INTEGER NOT NULL,
  sha256             TEXT NOT NULL,
  storage_key        TEXT NOT NULL,
  uploaded_by        TEXT NOT NULL REFERENCES users(id),
  uploaded_at        TEXT NOT NULL,
  retention_until    TEXT,
  legal_hold         INTEGER NOT NULL DEFAULT 0,
  content_deleted_at TEXT,
  content_deleted_by TEXT,
  scan_status        TEXT NOT NULL DEFAULT 'NOT_SCANNED'
);

CREATE TABLE document_access_log (
  id          TEXT PRIMARY KEY,
  document_id TEXT NOT NULL,
  user_id     TEXT,
  action      TEXT NOT NULL,
  granted     INTEGER NOT NULL,
  reason      TEXT,
  at          TEXT NOT NULL
);

-- ---------------------------------------------------------------- evidence (claims are APPEND-ONLY; status is a separate append-only stream)
-- A claim is a snapshot of operator/dispatcher-entered values for one requirement.
-- Editing a profile or job field creates a NEW claim that supersedes the old one.
CREATE TABLE evidence_claims (
  id                TEXT PRIMARY KEY,
  owner_operator_id TEXT REFERENCES owner_operators(id),
  gate              TEXT NOT NULL CHECK (gate IN ('ASSET','TRUCK','POWER','SITE')),
  subject_type      TEXT NOT NULL,
  subject_id        TEXT NOT NULL,
  claim_key         TEXT NOT NULL,
  claimed_json      TEXT NOT NULL,
  document_ids_json TEXT NOT NULL DEFAULT '[]',
  supersedes_id     TEXT REFERENCES evidence_claims(id),
  entered_by        TEXT NOT NULL REFERENCES users(id),
  entered_at        TEXT NOT NULL,
  policy_version    INTEGER NOT NULL
);
CREATE INDEX idx_claims_subject ON evidence_claims(subject_type, subject_id, claim_key);

CREATE TABLE evidence_status_events (
  id                 TEXT PRIMARY KEY,
  claim_id           TEXT NOT NULL REFERENCES evidence_claims(id),
  status             TEXT NOT NULL CHECK (status IN ('OPERATOR_ENTERED','PENDING','VERIFIED','UNCONFIRMED','REJECTED')),
  actor_id           TEXT NOT NULL REFERENCES users(id),
  actor_role         TEXT NOT NULL,
  note               TEXT,
  basis              TEXT,
  supporting_message_id TEXT,
  policy_version     INTEGER NOT NULL,
  at                 TEXT NOT NULL,
  seq                INTEGER NOT NULL
);
CREATE INDEX idx_evstatus_claim ON evidence_status_events(claim_id, seq);

-- Gate-level sign-off by a qualification officer (APPEND-ONLY)
CREATE TABLE gate_reviews (
  id             TEXT PRIMARY KEY,
  gate           TEXT NOT NULL CHECK (gate IN ('ASSET','TRUCK','POWER','SITE')),
  subject_type   TEXT NOT NULL,
  subject_id     TEXT NOT NULL,
  decision       TEXT NOT NULL CHECK (decision IN ('VERIFIED','FAILED')),
  reviewer_id    TEXT NOT NULL REFERENCES users(id),
  note           TEXT NOT NULL,
  policy_version INTEGER NOT NULL,
  claim_ids_json TEXT NOT NULL,
  at             TEXT NOT NULL,
  seq            INTEGER NOT NULL
);
CREATE INDEX idx_gate_reviews_subject ON gate_reviews(subject_type, subject_id, gate, seq);

-- ---------------------------------------------------------------- jobs
CREATE TABLE jobs (
  id                     TEXT PRIMARY KEY,
  quote_ref              TEXT NOT NULL UNIQUE,
  stage                  TEXT NOT NULL CHECK (stage IN ('QUOTE','SPEC','SET','DISPATCHED','ARRIVED','DELIVERED','POD_RECORDED','SEALED','CANCELLED')),
  policy_version         INTEGER NOT NULL REFERENCES policy_versions(version),
  customer_name          TEXT NOT NULL,
  required_asset_class   TEXT,
  pickup_location        TEXT,
  pickup_lat             REAL,
  pickup_lng             REAL,
  delivery_address       TEXT,
  delivery_lat           REAL,
  delivery_lng           REAL,
  window_start           TEXT,
  window_end             TEXT,
  site_contact_name      TEXT,
  site_contact_phone     TEXT,
  site_contact_method    TEXT,
  site_access_notes      TEXT,
  cable_run_ft           REAL,
  setpoint_f             REAL,
  commodity              TEXT,
  commodity_notes        TEXT,
  site_power_status      TEXT CHECK (site_power_status IN ('AVAILABLE','UNAVAILABLE','UNKNOWN')),
  site_voltage           INTEGER,
  site_phase             TEXT,
  site_amperage          INTEGER,
  site_connector         TEXT,
  assigned_owner_operator_id TEXT REFERENCES owner_operators(id),
  assigned_driver_id     TEXT REFERENCES drivers(id),
  assigned_truck_id      TEXT REFERENCES trucks(id),
  assigned_asset_id      TEXT REFERENCES cold_assets(id),
  assigned_power_id      TEXT REFERENCES power_configs(id),
  last_evaluation_json   TEXT,
  dispatched_at          TEXT,
  dispatched_by          TEXT,
  arrived_at             TEXT,
  delivered_at           TEXT,
  pod_recorded_at        TEXT,
  sealed_at              TEXT,
  is_demo                INTEGER NOT NULL DEFAULT 0,
  created_by             TEXT NOT NULL REFERENCES users(id),
  created_at             TEXT NOT NULL,
  updated_at             TEXT NOT NULL
);

CREATE TABLE pods (
  id                 TEXT PRIMARY KEY,
  job_id             TEXT NOT NULL REFERENCES jobs(id),
  receiver_name      TEXT NOT NULL,
  received_at        TEXT NOT NULL,
  delivered_temp_f   REAL,
  notes              TEXT,
  document_ids_json  TEXT NOT NULL DEFAULT '[]',
  recorded_by        TEXT NOT NULL REFERENCES users(id),
  recorded_at        TEXT NOT NULL
);

-- ---------------------------------------------------------------- Proof Vault ledger (APPEND-ONLY, hash-chained)
CREATE TABLE ledger_events (
  seq                    INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id               TEXT NOT NULL UNIQUE,
  entity_type            TEXT NOT NULL,
  entity_id              TEXT NOT NULL,
  event_type             TEXT NOT NULL,
  actor_user_id          TEXT,
  occurred_at            TEXT NOT NULL,
  recorded_at            TEXT NOT NULL,
  policy_version         INTEGER,
  payload_json           TEXT NOT NULL,
  evidence_reference_ids TEXT NOT NULL DEFAULT '[]',
  related_event_id       TEXT,
  previous_event_hash    TEXT NOT NULL,
  event_hash             TEXT NOT NULL UNIQUE
);
CREATE INDEX idx_ledger_entity ON ledger_events(entity_type, entity_id, seq);

CREATE TABLE sealed_manifests (
  id                    TEXT PRIMARY KEY,
  job_id                TEXT NOT NULL REFERENCES jobs(id),
  version               INTEGER NOT NULL,
  supersedes_manifest_id TEXT REFERENCES sealed_manifests(id),
  manifest_json         TEXT NOT NULL,
  manifest_hash         TEXT NOT NULL,
  last_event_hash       TEXT NOT NULL,
  sealed_by             TEXT NOT NULL REFERENCES users(id),
  sealed_at             TEXT NOT NULL,
  policy_version        INTEGER NOT NULL,
  UNIQUE (job_id, version)
);

-- ---------------------------------------------------------------- invoices
CREATE TABLE invoices (
  id                TEXT PRIMARY KEY,
  number            TEXT NOT NULL UNIQUE,
  job_id            TEXT REFERENCES jobs(id),
  owner_operator_id TEXT REFERENCES owner_operators(id),
  bill_to_name      TEXT NOT NULL,
  status            TEXT NOT NULL CHECK (status IN ('DRAFT','ISSUED','PAID','PARTIALLY_PAID','VOID')),
  currency          TEXT NOT NULL DEFAULT 'USD',
  due_date          TEXT,
  notes             TEXT,
  issued_at         TEXT,
  is_demo           INTEGER NOT NULL DEFAULT 0,
  created_by        TEXT NOT NULL REFERENCES users(id),
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);

CREATE TABLE invoice_line_items (
  id               TEXT PRIMARY KEY,
  invoice_id       TEXT NOT NULL REFERENCES invoices(id),
  category         TEXT NOT NULL,
  description      TEXT NOT NULL,
  quantity         REAL NOT NULL CHECK (quantity > 0),
  unit_price_cents INTEGER NOT NULL CHECK (unit_price_cents >= 0),
  amount_cents     INTEGER NOT NULL,
  created_at       TEXT NOT NULL
);

CREATE TABLE payments (
  id           TEXT PRIMARY KEY,
  invoice_id   TEXT NOT NULL REFERENCES invoices(id),
  amount_cents INTEGER NOT NULL CHECK (amount_cents > 0),
  received_at  TEXT NOT NULL,
  method_note  TEXT,
  recorded_by  TEXT NOT NULL REFERENCES users(id),
  recorded_at  TEXT NOT NULL
);

-- ---------------------------------------------------------------- crew communication (APPEND-ONLY)
CREATE TABLE job_messages (
  id         TEXT PRIMARY KEY,
  job_id     TEXT NOT NULL REFERENCES jobs(id),
  author_id  TEXT NOT NULL REFERENCES users(id),
  body       TEXT NOT NULL,
  created_at TEXT NOT NULL
);

-- ---------------------------------------------------------------- append-only guards
CREATE TRIGGER ledger_no_update BEFORE UPDATE ON ledger_events BEGIN SELECT RAISE(ABORT, 'ledger_events is append-only'); END;
CREATE TRIGGER ledger_no_delete BEFORE DELETE ON ledger_events BEGIN SELECT RAISE(ABORT, 'ledger_events is append-only'); END;
CREATE TRIGGER manifests_no_update BEFORE UPDATE ON sealed_manifests BEGIN SELECT RAISE(ABORT, 'sealed_manifests is append-only'); END;
CREATE TRIGGER manifests_no_delete BEFORE DELETE ON sealed_manifests BEGIN SELECT RAISE(ABORT, 'sealed_manifests is append-only'); END;
CREATE TRIGGER claims_no_update BEFORE UPDATE ON evidence_claims BEGIN SELECT RAISE(ABORT, 'evidence_claims is append-only'); END;
CREATE TRIGGER claims_no_delete BEFORE DELETE ON evidence_claims BEGIN SELECT RAISE(ABORT, 'evidence_claims is append-only'); END;
CREATE TRIGGER evstatus_no_update BEFORE UPDATE ON evidence_status_events BEGIN SELECT RAISE(ABORT, 'evidence_status_events is append-only'); END;
CREATE TRIGGER evstatus_no_delete BEFORE DELETE ON evidence_status_events BEGIN SELECT RAISE(ABORT, 'evidence_status_events is append-only'); END;
CREATE TRIGGER gate_reviews_no_update BEFORE UPDATE ON gate_reviews BEGIN SELECT RAISE(ABORT, 'gate_reviews is append-only'); END;
CREATE TRIGGER gate_reviews_no_delete BEFORE DELETE ON gate_reviews BEGIN SELECT RAISE(ABORT, 'gate_reviews is append-only'); END;
CREATE TRIGGER policy_no_update BEFORE UPDATE ON policy_versions BEGIN SELECT RAISE(ABORT, 'policy_versions is append-only'); END;
CREATE TRIGGER policy_no_delete BEFORE DELETE ON policy_versions BEGIN SELECT RAISE(ABORT, 'policy_versions is append-only'); END;
CREATE TRIGGER messages_no_update BEFORE UPDATE ON job_messages BEGIN SELECT RAISE(ABORT, 'job_messages is append-only'); END;
CREATE TRIGGER messages_no_delete BEFORE DELETE ON job_messages BEGIN SELECT RAISE(ABORT, 'job_messages is append-only'); END;
CREATE TRIGGER pods_no_update BEFORE UPDATE ON pods BEGIN SELECT RAISE(ABORT, 'pods is append-only; record a correction event'); END;
CREATE TRIGGER pods_no_delete BEFORE DELETE ON pods BEGIN SELECT RAISE(ABORT, 'pods is append-only'); END;
CREATE TRIGGER access_log_no_update BEFORE UPDATE ON document_access_log BEGIN SELECT RAISE(ABORT, 'document_access_log is append-only'); END;
CREATE TRIGGER access_log_no_delete BEFORE DELETE ON document_access_log BEGIN SELECT RAISE(ABORT, 'document_access_log is append-only'); END;
-- Documents: metadata rows are never deleted (retention purges content only).
CREATE TRIGGER documents_no_delete BEFORE DELETE ON documents BEGIN SELECT RAISE(ABORT, 'document metadata is retained; purge content via retention workflow'); END;
CREATE TRIGGER documents_immutable_fields BEFORE UPDATE OF sha256, storage_key, uploaded_by, uploaded_at, original_filename ON documents
BEGIN SELECT RAISE(ABORT, 'document identity fields are immutable'); END;
-- Payments are append-only; reversals are recorded as ledger events.
CREATE TRIGGER payments_no_update BEFORE UPDATE ON payments BEGIN SELECT RAISE(ABORT, 'payments are append-only'); END;
CREATE TRIGGER payments_no_delete BEFORE DELETE ON payments BEGIN SELECT RAISE(ABORT, 'payments are append-only'); END;
